from enum import Enum

ZERO_ADDRESS = "0x0000000000000000000000000000000000000000"
AMOY = 80002
POLYGON = 137
END_CURSOR = "LTE="
L0 = 0
L1 = 1
L2 = 2

class Environment(str, Enum):
    POLYMARKET_PRIVATE_KEY = "POLYMARKET_PRIVATE_KEY"
    POLYMARKET_PROXY_ADDRESS = "POLYMARKET_PROXY_ADDRESS"
    POLYGON_RPC = "POLYGON_RPC"
    GRAPH_API_KEY = "GRAPH_API_KEY"
    POLY_SUBGRAPH_ID = "POLY_SUBGRAPH_ID"
    METAMASK_PRIVATE_KEY = "METAMASK_PRIVATE_KEY"
    METAMASK_ADDRESS = "METAMASK_ADDRESS"
    POLYMARKET_CLOB_HOST = "POLYMARKET_CLOB_HOST"

class OrderType(str, Enum):
    GTC = "GTC"
    FOK = "FOK"
    GTD = "GTD"
    FAK = "FAK"


class AssetType(str, Enum):
    COLLATERAL = "COLLATERAL"
    CONDITIONAL = "CONDITIONAL"